name: Pull Request CI
on: [ push ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black
        uses: microsoft/action-python@0.7.2
        with:
          workdir: .
          black: true
          python_version: "3.12"
      - name: Flake8
        uses: microsoft/action-python@0.7.2
        with:
          workdir: .
          flake8: true
          python_version: "3.12"

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
            **/requirements-dev.txt
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Pytest
        run: |
          python -m pytest
