name: Pull Request CI
on: [ push ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          workdir: .
          black: true
      - name: Flake8
        uses: microsoft/action-python@0.7.0
        with:
          workdir: .
          flake8: true

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:
          workdir: .
          testing: true
          python_version: ${{ matrix.python-version }}
