name: Pull Request CI
on: [ push ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black (examples)
        uses: microsoft/action-python@0.7.2
        with:
          workdir: examples
          black: true
      - name: Black (godaddypy)
        uses: microsoft/action-python@0.7.2
        with:
          workdir: godaddypy
          black: true
      - name: Black (tests)
        uses: microsoft/action-python@0.7.2
        with:
          workdir: tests
          black: true
      - name: Flake8
        uses: microsoft/action-python@0.7.2
        with:
          workdir: .
          flake8: true

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Pytest
        uses: microsoft/action-python@0.7.2
        with:
          workdir: .
          pytest: true
          python_version: ${{ matrix.python-version }}
